spring:
  datasource:
    platform : postgres
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password : postgres

  jpa :
    generate-ddl : true
    properties :
      hibernate :
        jdbc :
          lob :
            non_contextual_creation : true